name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=20.3.3
  - mlflow=2.3.2
  - hydra-core=1.0.6
  - pyarrow=8.0.0
  - pip:
      - wandb==0.15.3
      - hydra-joblib-launcher==1.1.2
      - protobuf==3.20.*
