wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.15
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685119856.980603
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.8.15
      5: 0.15.3
      8:
      - 3
      - 5
